define n = Character(None, what_italic=True)
define c = Character("Cyra", color="#ff92d2", image="cyra")
define s = Character("Seren", color="#ba91cd", image="seren")
define b = Character("Bot", color="#83d692", image="bot")
define d = Character("Drone", color="#838bd6", image="drone")
define u = Character("Unknown", color="#aab0ac", image="drone")
define p = Character("[player]", color="#f4c77a")
define a = Character("Agent", color="#cb1010", image="drone")
define g = Character("Grandmother Agent", color="#cc6fcc")