define c = Character("Cyra", color="#ff92d2", image="cyra")
define s = Character("Seren", color="#ba91cd", image="seren")
define b = Character("Bot", color="#83d692", image="bot")
define d = Character("Drone", color="#83d692", image="drone")
define p = Character("[player]", color="#f4c77a")
